version: "3.1"

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file: .env.prod
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/westapi
      - node_modules:/usr/src/westapi/node_modules
    networks:
      - app-network
    links:
      - db
  db:
    container_name: mongoDB
    image: mongo:latest
    restart: always
    volumes:
      - westapidata:/data/db
    environment:
      - MONGO_INITDB_DATABASE= WestApi
    ports:
      - 27017:27017
    networks:
      - app-network  

volumes:
  westapidata:
    external: true
  node_modules:

networks:
  app-network:
    driver: bridge